name: LINE Bot Daily Message

on:
  schedule:
    # 毎日9時（日本時間）に実行
    - cron: '0 0 * * *'  # UTCで0時 = 日本時間9時
  workflow_dispatch:    # 手動実行用

jobs:
  send_line:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 依存パッケージインストール
        run: pip install line-bot-sdk

      - name: LINE送信スクリプト実行
        run: python send_message.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
